language: csharp
dist: trusty
sudo: false
solution: FluentMigrator.sln
mono: latest
dotnet: 2.1.103
script:
- dotnet build ./FluentMigrator.sln
- dotnet vstest test/FluentMigrator.Tests/bin/Debug/net461/FluentMigrator.Tests.dll
  --TestCaseFilter:'TestCategory!=NotWorkingOnMono&(TestCategory!=Integration|(TestCategory=Integration&(TestCategory=SQLite)))'
